name: CI

on:
  push:
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Import check
        run: |
          python - << 'PY'
          for mod in ["numpy","pandas","scipy","matplotlib","yfinance","jupyter"]:
              __import__(mod)
          print("Imports OK")
          PY
